### ISSUE TITLE
Build for specific targets

### ISSUE THREAD

**Issue by KwatME** [GSEA-MSigDB/GSEA.jl#21]

**Comment by KwatME** [comment]
https://github.com/JuliaLang/PackageCompiler.jl/issues/663

**Comment by KwatME** [comment]
#26

**Comment by KwatME** [comment]
When all issues on macOS (interface, numbers, and everything else) are taken cared of we will build for Windows via https://julialang.github.io/PackageCompiler.jl/dev/devdocs/binaries_part_2.html#Windows-specific-flags.

**Comment by KwatME** [comment]
Building for Linux can be done already by commenting out browser plotting in runtests.jl and sarcopenia.jl.

**Comment by KwatME** [comment]
https://github.com/korbinian90/CompileMRI.jl/blob/master/.github/workflows/compile.yml

```
name: Compile
on:
  release:
    types: [published]
jobs:
  compile:
    name: Julia 1.7 - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7'
          arch: 'x64'
      - uses: julia-actions/julia-buildpkg@latest
      - name: Compile
        run: julia --color=yes --project=@. -e 'using CompileMRI; compile()'
      - name: Get Version
        run: echo "::set-output name=version::$(julia --project=@. -e 'using CompileMRI; println(CompileMRI.mritools_version())')"
        id: version
      - name: Compress Unix
        if: ${{ runner.os != 'Windows' }}
        run: |
          echo "ZIP_ENDING=tar.gz" >> $GITHUB_ENV
          echo "ZIP_TYPE=gzip" >> $GITHUB_ENV
          mv compiled mritools_${{ runner.os }}_${{ steps.version.outputs.version }}
          tar -vczf mritools_${{ runner.os }}_${{ steps.version.outputs.version }}.tar.gz mritools_${{ runner.os }}_${{ steps.version.outputs.version }}
      - name: Compress Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo "ZIP_ENDING=zip" >> $env:GITHUB_ENV
          echo "ZIP_TYPE=zip" >> $env:GITHUB_ENV
          Compress-Archive -Path 'compiled/*' -DestinationPath 'mritools_${{ runner.os }}_${{ steps.version.outputs.version }}.zip'
      - name: Upload release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./mritools_${{ runner.os }}_${{ steps.version.outputs.version }}.${{ env.ZIP_ENDING }}
          asset_name: mritools_${{ runner.os }}_${{ steps.version.outputs.version }}.${{ env.ZIP_ENDING }}
          asset_content_type: application/${{ env.ZIP_TYPE }}
```
